version: "3.7"

services:
  kratos-migrate:
    container_name: kratos-migrate
    image: oryd/kratos:latest-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/config.yml migrate sql sql -e --yes # https://www.ory.sh/kratos/docs/cli/kratos-migrate-sql
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    container_name: kratos
    image: oryd/kratos:latest-sqlite
    ports:
      - "4433:4433"
      - "4434:4434"
    restart: unless-stopped
    command: serve -c /etc/config/kratos/config.yml --dev
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet

  oathkeeper:
    container_name: oathkeeper
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    ports:
      - 4455:4455
      - 4456:4456
    command: serve proxy -c /etc/config/oathkeeper/config.yml
    volumes:
      - type: bind
        source: ./oathkeeper
        target: /etc/config/oathkeeper
    networks:
      - intranet

  mailslurper:
    container_name: mailslurper
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
  intranet:

volumes:
  kratos-sqlite:
